### ISSUE TITLE
Possible Resource Exception

### ISSUE THREAD

**Issue by andrewxcav** [xmos/lib_src#124]
The delay_*() functions assume that there is an available, initialized timer resource but does not check or guarantee that this is the case:

Here is a usage that does not currently cause a resource exception, but may if more timers were in use:
https://github.com/xmos/lib_src/blame/54d83c283da57a20f3167fefacb7f6275d1193d7/lib_src/src/asrc_task/asrc_task.c#L262

**Comment by ed-xmos** [comment]
Addressed in https://github.com/xmos/lib_src/pull/130

**Comment by ed-xmos** [comment]
Weirdly this was nothing to do with time. It was a resource call causing volatility of struct not explicitly marked as volatile. Took a while to work it out but removed a TODO now which is always nice.
