### ISSUE TITLE
Add cmake support

### ISSUE THREAD

**Issue by xhuw** [xmos/lib_src#62]
Currently cmake support is being manually copied about through projects using this repo. 

the CMakeLists.txt from [here](https://github.com/xmos/sln_voice/blob/develop/modules/sample_rate_conversion/CMakeLists.txt) should be good enough

**Comment by mbanth** [comment]
@xhuw, please provide a Story Point value for this issue.  In making the changes you have proposed, please bear in mind that this repository is publicly visible.
